-- 생성자 Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   위치:        2021-07-02 07:11:36 KST
--   사이트:      Oracle Database 11g
--   유형:      Oracle Database 11g




CREATE TABLE studydb.tbl_admin_menu (
    type     VARCHAR2(20 BYTE) NOT NULL,
    name     VARCHAR2(20 BYTE),
    orders   NUMBER(11),
    parent   VARCHAR2(20 BYTE)
)
PCTFREE 10 PCTUSED 40 TABLESPACE users LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
    DEFAULT );

ALTER TABLE studydb.tbl_admin_menu
    ADD CONSTRAINT tbl_admin_menu_pk PRIMARY KEY ( type )
        USING INDEX PCTFREE 10 INITRANS 2 TABLESPACE users LOGGING
            STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
            DEFAULT );
CREATE TABLE studydb.tbl_board (
    idx           NUMBER(22) NOT NULL,
    title         VARCHAR2(100 BYTE),
    content       VARCHAR2(255 BYTE),
    writer        VARCHAR2(100 BYTE),
    viewcount     NUMBER(11),
    reg_date      DATE,
    update_date   DATE,
    type          VARCHAR2(20 BYTE)
)
PCTFREE 10 PCTUSED 40 TABLESPACE users LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
    DEFAULT );

ALTER TABLE studydb.tbl_board
    ADD CONSTRAINT tbl_board_pk PRIMARY KEY ( idx )
        USING INDEX PCTFREE 10 INITRANS 2 TABLESPACE users LOGGING
            STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
            DEFAULT );
CREATE TABLE studydb.tbl_board_attach (
    save_file_name   VARCHAR2(255 BYTE) NOT NULL,
    real_file_name   VARCHAR2(255 BYTE),
    reg_date         DATE,
    board_idx        NUMBER(22)
)
PCTFREE 10 PCTUSED 40 TABLESPACE users LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
    DEFAULT );

ALTER TABLE studydb.tbl_board_attach
    ADD CONSTRAINT tbl_board_attach_pk PRIMARY KEY ( save_file_name )
        USING INDEX PCTFREE 10 INITRANS 2 TABLESPACE users LOGGING
            STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
            DEFAULT );
CREATE TABLE studydb.tbl_board_reply (
    idx           NUMBER(22) NOT NULL,
    content       VARCHAR2(255 BYTE),
    writer        VARCHAR2(100 BYTE),
    reg_date      DATE,
    update_date   DATE,
    board_idx     NUMBER(22)
)
PCTFREE 10 PCTUSED 40 TABLESPACE users LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
    DEFAULT );

ALTER TABLE studydb.tbl_board_reply
    ADD CONSTRAINT tbl_board_reply_pk PRIMARY KEY ( idx )
        USING INDEX PCTFREE 10 INITRANS 2 TABLESPACE users LOGGING
            STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
            DEFAULT );
CREATE TABLE studydb.tbl_home_menu (
    type     VARCHAR2(20 BYTE) NOT NULL,
    name     VARCHAR2(20 BYTE),
    orders   NUMBER(11),
    parent   VARCHAR2(20 BYTE)
)
PCTFREE 10 PCTUSED 40 TABLESPACE users LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
    DEFAULT );

ALTER TABLE studydb.tbl_home_menu
    ADD CONSTRAINT tbl_home_menu_pk PRIMARY KEY ( type )
        USING INDEX PCTFREE 10 INITRANS 2 TABLESPACE users LOGGING
            STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
            DEFAULT );
ALTER TABLE studydb.tbl_admin_menu
    ADD CONSTRAINT amptype FOREIGN KEY ( parent )
        REFERENCES studydb.tbl_admin_menu ( type )
            ON DELETE CASCADE
    NOT DEFERRABLE;
ALTER TABLE studydb.tbl_board
    ADD CONSTRAINT board_type_fk FOREIGN KEY ( type )
        REFERENCES studydb.tbl_board_type ( type )
            ON DELETE CASCADE
    NOT DEFERRABLE;
ALTER TABLE studydb.tbl_board_attach
    ADD CONSTRAINT board_index_fk FOREIGN KEY ( board_idx )
        REFERENCES studydb.tbl_board ( idx )
            ON DELETE CASCADE
    NOT DEFERRABLE;
ALTER TABLE studydb.tbl_board_reply
    ADD CONSTRAINT board_index_reply_fk FOREIGN KEY ( board_idx )
        REFERENCES studydb.tbl_board ( idx )
            ON DELETE CASCADE
    NOT DEFERRABLE;
ALTER TABLE studydb.tbl_home_menu
    ADD CONSTRAINT mptype FOREIGN KEY ( parent )
        REFERENCES studydb.tbl_home_menu ( type )
            ON DELETE CASCADE
    NOT DEFERRABLE;